# see https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component for more component conf info
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carbonio-storages-ce
  title: Carbonio Storages CE (Node/JS/TS SDK)
  description: External files store application for Carbonio CE
  tags:
    - node
    - github
spec:
  type: library
  lifecycle: production
  owner: glistening-killers
